# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/My_Counter.xdc

# Block Designs: bd/My_Counter/My_Counter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==My_Counter || ORIG_REF_NAME==My_Counter} -quiet] -quiet

# IP: bd/My_Counter/ip/My_Counter_processing_system7_0_0/My_Counter_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==My_Counter_processing_system7_0_0 || ORIG_REF_NAME==My_Counter_processing_system7_0_0} -quiet] -quiet

# IP: bd/My_Counter/ip/My_Counter_counter_0_0/My_Counter_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==My_Counter_counter_0_0 || ORIG_REF_NAME==My_Counter_counter_0_0} -quiet] -quiet

# XDC: bd/My_Counter/My_Counter_ooc.xdc
