# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FYP/Zybo/Program_Bin_File/Program_Bin_File.srcs/sources_1/bd/My_Counter/ip/My_Counter_processing_system7_0_0/My_Counter_processing_system7_0_0.xci
# IP: The module: 'My_Counter_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FYP/Zybo/Program_Bin_File/Program_Bin_File.srcs/sources_1/bd/My_Counter/ip/My_Counter_processing_system7_0_0/My_Counter_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'My_Counter_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/FYP/Zybo/Program_Bin_File/Program_Bin_File.srcs/sources_1/bd/My_Counter/ip/My_Counter_processing_system7_0_0/My_Counter_processing_system7_0_0.xci
# IP: The module: 'My_Counter_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FYP/Zybo/Program_Bin_File/Program_Bin_File.srcs/sources_1/bd/My_Counter/ip/My_Counter_processing_system7_0_0/My_Counter_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'My_Counter_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
