# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Zybo_Counter/Zybo_Counter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_Counter || ORIG_REF_NAME==Zybo_Counter} -quiet] -quiet

# IP: bd/Zybo_Counter/ip/Zybo_Counter_processing_system7_0_0/Zybo_Counter_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_Counter_processing_system7_0_0 || ORIG_REF_NAME==Zybo_Counter_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zybo_Counter/ip/Zybo_Counter_axi_gpio_0_0/Zybo_Counter_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_Counter_axi_gpio_0_0 || ORIG_REF_NAME==Zybo_Counter_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Zybo_Counter/ip/Zybo_Counter_ps7_0_axi_periph_0/Zybo_Counter_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_Counter_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zybo_Counter_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zybo_Counter/ip/Zybo_Counter_rst_ps7_0_100M_0/Zybo_Counter_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_Counter_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zybo_Counter_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Zybo_Counter/ip/Zybo_Counter_auto_pc_0/Zybo_Counter_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zybo_Counter_auto_pc_0 || ORIG_REF_NAME==Zybo_Counter_auto_pc_0} -quiet] -quiet

# XDC: bd/Zybo_Counter/Zybo_Counter_ooc.xdc
