# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Led_Switch_Buttons/Led_Switch_Buttons.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Led_Switch_Buttons || ORIG_REF_NAME==Led_Switch_Buttons} -quiet] -quiet

# IP: bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_processing_system7_0_0/Led_Switch_Buttons_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Led_Switch_Buttons_processing_system7_0_0 || ORIG_REF_NAME==Led_Switch_Buttons_processing_system7_0_0} -quiet] -quiet

# IP: bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_0_0/Led_Switch_Buttons_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Led_Switch_Buttons_axi_gpio_0_0 || ORIG_REF_NAME==Led_Switch_Buttons_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_1_0/Led_Switch_Buttons_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Led_Switch_Buttons_axi_gpio_1_0 || ORIG_REF_NAME==Led_Switch_Buttons_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_ps7_0_axi_periph_0/Led_Switch_Buttons_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Led_Switch_Buttons_ps7_0_axi_periph_0 || ORIG_REF_NAME==Led_Switch_Buttons_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_rst_ps7_0_100M_0/Led_Switch_Buttons_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Led_Switch_Buttons_rst_ps7_0_100M_0 || ORIG_REF_NAME==Led_Switch_Buttons_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_xbar_0/Led_Switch_Buttons_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Led_Switch_Buttons_xbar_0 || ORIG_REF_NAME==Led_Switch_Buttons_xbar_0} -quiet] -quiet

# IP: bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_auto_pc_0/Led_Switch_Buttons_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Led_Switch_Buttons_auto_pc_0 || ORIG_REF_NAME==Led_Switch_Buttons_auto_pc_0} -quiet] -quiet

# XDC: bd/Led_Switch_Buttons/Led_Switch_Buttons_ooc.xdc
