# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FYP/FPGA_XILINX 2/ROM_Using_IP_With_MATLAB/ROM_Using_IP_With_MATLAB.srcs/sources_1/bd/ROM_Using_IP_With_MATLAB/ip/ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0/ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0.xci
# IP: The module: 'ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FYP/FPGA_XILINX 2/ROM_Using_IP_With_MATLAB/ROM_Using_IP_With_MATLAB.srcs/sources_1/bd/ROM_Using_IP_With_MATLAB/ip/ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0/ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/FYP/FPGA_XILINX 2/ROM_Using_IP_With_MATLAB/ROM_Using_IP_With_MATLAB.srcs/sources_1/bd/ROM_Using_IP_With_MATLAB/ip/ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0/ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0.xci
# IP: The module: 'ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FYP/FPGA_XILINX 2/ROM_Using_IP_With_MATLAB/ROM_Using_IP_With_MATLAB.srcs/sources_1/bd/ROM_Using_IP_With_MATLAB/ip/ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0/ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_Using_IP_With_MATLAB_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
