# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/NAND_Gate.xdc

# Block Designs: bd/NAND_Gate/NAND_Gate.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND_Gate || ORIG_REF_NAME==NAND_Gate} -quiet] -quiet

# IP: bd/NAND_Gate/ip/NAND_Gate_processing_system7_0_0/NAND_Gate_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND_Gate_processing_system7_0_0 || ORIG_REF_NAME==NAND_Gate_processing_system7_0_0} -quiet] -quiet

# IP: bd/NAND_Gate/ip/NAND_Gate_axi_gpio_0_0/NAND_Gate_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND_Gate_axi_gpio_0_0 || ORIG_REF_NAME==NAND_Gate_axi_gpio_0_0} -quiet] -quiet

# IP: bd/NAND_Gate/ip/NAND_Gate_axi_gpio_0_1/NAND_Gate_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND_Gate_axi_gpio_0_1 || ORIG_REF_NAME==NAND_Gate_axi_gpio_0_1} -quiet] -quiet

# IP: bd/NAND_Gate/ip/NAND_Gate_AND_Gate_0_0/NAND_Gate_AND_Gate_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND_Gate_AND_Gate_0_0 || ORIG_REF_NAME==NAND_Gate_AND_Gate_0_0} -quiet] -quiet

# IP: bd/NAND_Gate/ip/NAND_Gate_ps7_0_axi_periph_0/NAND_Gate_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND_Gate_ps7_0_axi_periph_0 || ORIG_REF_NAME==NAND_Gate_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/NAND_Gate/ip/NAND_Gate_rst_ps7_0_100M_0/NAND_Gate_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND_Gate_rst_ps7_0_100M_0 || ORIG_REF_NAME==NAND_Gate_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/NAND_Gate/ip/NAND_Gate_xbar_0/NAND_Gate_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND_Gate_xbar_0 || ORIG_REF_NAME==NAND_Gate_xbar_0} -quiet] -quiet

# IP: bd/NAND_Gate/ip/NAND_Gate_auto_pc_0/NAND_Gate_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==NAND_Gate_auto_pc_0 || ORIG_REF_NAME==NAND_Gate_auto_pc_0} -quiet] -quiet

# XDC: bd/NAND_Gate/NAND_Gate_ooc.xdc
