# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.cache/wt [current_project]
set_property parent.project_path E:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:2.0 [current_project]
set_property ip_output_repo e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib E:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/hdl/NAND_Gate_wrapper.v
add_files E:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/NAND_Gate.bd
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_processing_system7_0_0/NAND_Gate_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_axi_gpio_0_0/NAND_Gate_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_axi_gpio_0_0/NAND_Gate_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_axi_gpio_0_0/NAND_Gate_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_axi_gpio_0_1/NAND_Gate_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_axi_gpio_0_1/NAND_Gate_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_axi_gpio_0_1/NAND_Gate_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_rst_ps7_0_100M_0/NAND_Gate_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_rst_ps7_0_100M_0/NAND_Gate_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_rst_ps7_0_100M_0/NAND_Gate_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_xbar_0/NAND_Gate_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/ip/NAND_Gate_auto_pc_0/NAND_Gate_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/sources_1/bd/NAND_Gate/NAND_Gate_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/constrs_1/new/NAND_Gate.xdc
set_property used_in_implementation false [get_files E:/FYP/Zybo/Interfacing_PS_With_PL_ZYBO/Interfacing_PS_With_PL_ZYBO.srcs/constrs_1/new/NAND_Gate.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NAND_Gate_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NAND_Gate_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NAND_Gate_wrapper_utilization_synth.rpt -pb NAND_Gate_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
