# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Test.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_UART_Tx_Rx_0_0/design_1_UART_Tx_Rx_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_UART_Tx_Rx_0_0 || ORIG_REF_NAME==design_1_UART_Tx_Rx_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_Diff_Clk_0_0/design_1_Diff_Clk_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_Diff_Clk_0_0 || ORIG_REF_NAME==design_1_Diff_Clk_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_1/design_1_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_1 || ORIG_REF_NAME==design_1_ila_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_1/design_1_vio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vio_0_1 || ORIG_REF_NAME==design_1_vio_0_1} -quiet] -quiet

# XDC: c:/Users/NESLS023/Desktop/UART_Tests/UART_Test_Course_V3/Poject_1.gen/sources_1/bd/design_1/design_1_ooc.xdc
