# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FYP/Zybo/Zynq_First_Example_LED_Using_Switch/Led_Switch_Buttons/Led_Switch_Buttons.srcs/sources_1/bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_0_0/Led_Switch_Buttons_axi_gpio_0_0.xci
# IP: The module: 'Led_Switch_Buttons_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FYP/Zybo/Zynq_First_Example_LED_Using_Switch/Led_Switch_Buttons/Led_Switch_Buttons.srcs/sources_1/bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_0_0/Led_Switch_Buttons_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Led_Switch_Buttons_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FYP/Zybo/Zynq_First_Example_LED_Using_Switch/Led_Switch_Buttons/Led_Switch_Buttons.srcs/sources_1/bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_0_0/Led_Switch_Buttons_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Led_Switch_Buttons_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FYP/Zybo/Zynq_First_Example_LED_Using_Switch/Led_Switch_Buttons/Led_Switch_Buttons.srcs/sources_1/bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_0_0/Led_Switch_Buttons_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Led_Switch_Buttons_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FYP/Zybo/Zynq_First_Example_LED_Using_Switch/Led_Switch_Buttons/Led_Switch_Buttons.srcs/sources_1/bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_0_0/Led_Switch_Buttons_axi_gpio_0_0.xci
# IP: The module: 'Led_Switch_Buttons_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FYP/Zybo/Zynq_First_Example_LED_Using_Switch/Led_Switch_Buttons/Led_Switch_Buttons.srcs/sources_1/bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_0_0/Led_Switch_Buttons_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Led_Switch_Buttons_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FYP/Zybo/Zynq_First_Example_LED_Using_Switch/Led_Switch_Buttons/Led_Switch_Buttons.srcs/sources_1/bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_0_0/Led_Switch_Buttons_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Led_Switch_Buttons_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FYP/Zybo/Zynq_First_Example_LED_Using_Switch/Led_Switch_Buttons/Led_Switch_Buttons.srcs/sources_1/bd/Led_Switch_Buttons/ip/Led_Switch_Buttons_axi_gpio_0_0/Led_Switch_Buttons_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Led_Switch_Buttons_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
