`timescale 1ns / 1ps
module single_port_ram
(
	input [7:0] data,
	input [5:0] addr,  // 6 bit address bus that maximum gives addresses from 0-63
	input we, clk,
	input cs,
	output [7:0] q
);

	// Declare the RAM variable
	reg [7:0] ram[63:0]; //8 bit with 64 addresses,addresses can be generated by [5:0]addr
	reg [7:0] temp;
	
always @ (posedge clk)
begin:write_process
	if (cs & we)
	ram[addr] <= data;
end
	
always@(posedge clk)
    begin:read_process
	if(cs & !we)
	temp<=ram[addr];	
end

assign q=temp;
	
endmodule
