# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DMA/DMA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA || ORIG_REF_NAME==DMA} -quiet] -quiet

# IP: bd/DMA/ip/DMA_processing_system7_0_0/DMA_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_processing_system7_0_0 || ORIG_REF_NAME==DMA_processing_system7_0_0} -quiet] -quiet

# IP: bd/DMA/ip/DMA_axi_dma_0_0/DMA_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_axi_dma_0_0 || ORIG_REF_NAME==DMA_axi_dma_0_0} -quiet] -quiet

# IP: bd/DMA/ip/DMA_axi_smc_0/DMA_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_axi_smc_0 || ORIG_REF_NAME==DMA_axi_smc_0} -quiet] -quiet

# IP: bd/DMA/ip/DMA_rst_ps7_0_100M_0/DMA_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_rst_ps7_0_100M_0 || ORIG_REF_NAME==DMA_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/DMA/ip/DMA_ps7_0_axi_periph_0/DMA_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_ps7_0_axi_periph_0 || ORIG_REF_NAME==DMA_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/DMA/ip/DMA_axis_data_fifo_0_0/DMA_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_axis_data_fifo_0_0 || ORIG_REF_NAME==DMA_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/DMA/ip/DMA_xlconcat_0_0/DMA_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_xlconcat_0_0 || ORIG_REF_NAME==DMA_xlconcat_0_0} -quiet] -quiet

# IP: bd/DMA/ip/DMA_auto_pc_0/DMA_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DMA_auto_pc_0 || ORIG_REF_NAME==DMA_auto_pc_0} -quiet] -quiet

# XDC: bd/DMA/DMA_ooc.xdc
