# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Full_Design/Full_Design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_Design || ORIG_REF_NAME==Full_Design} -quiet] -quiet

# IP: bd/Full_Design/ip/Full_Design_processing_system7_0_0/Full_Design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_Design_processing_system7_0_0 || ORIG_REF_NAME==Full_Design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Full_Design/ip/Full_Design_c_counter_binary_0_0/Full_Design_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_Design_c_counter_binary_0_0 || ORIG_REF_NAME==Full_Design_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/Full_Design/ip/Full_Design_axi_bram_ctrl_0_0/Full_Design_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_Design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Full_Design_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Full_Design/ip/Full_Design_blk_mem_gen_0_0/Full_Design_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_Design_blk_mem_gen_0_0 || ORIG_REF_NAME==Full_Design_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Full_Design/ip/Full_Design_Write_Data_0_0/Full_Design_Write_Data_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_Design_Write_Data_0_0 || ORIG_REF_NAME==Full_Design_Write_Data_0_0} -quiet] -quiet

# IP: bd/Full_Design/ip/Full_Design_ila_0_0/Full_Design_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_Design_ila_0_0 || ORIG_REF_NAME==Full_Design_ila_0_0} -quiet] -quiet

# IP: bd/Full_Design/ip/Full_Design_axi_smc_0/Full_Design_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_Design_axi_smc_0 || ORIG_REF_NAME==Full_Design_axi_smc_0} -quiet] -quiet

# IP: bd/Full_Design/ip/Full_Design_rst_ps7_0_100M_0/Full_Design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Full_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==Full_Design_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/Full_Design/Full_Design_ooc.xdc
